"""assets

Revision ID: 6b99ef3c52c5
Revises: 366b0cb127e3
Create Date: 2026-09-18 03:03:22.836871

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6b99ef3c52c5'
down_revision: str | None = '366b0cb127e3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column(
        'kind',
        sa.Enum(
            'original', 'generated', 'subject', 'background', 'mask', 'marketing', 'export',
            name='asset_kind', native_enum=False, length=16,
        ),
        nullable=False,
    ),
    sa.Column(
        'source',
        sa.Enum('upload', 'generate', 'tool', name='asset_source', native_enum=False, length=16),
        nullable=False,
    ),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('image_format', sa.String(length=8), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('has_alpha', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column(
        'created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
