"""agent runs

Revision ID: 43c2712f8543
Revises: a246b2fc911c
Create Date: 2026-09-19 02:41:28.168485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43c2712f8543'
down_revision: Union[str, None] = 'a246b2fc911c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('reply', sa.Text(), nullable=False),
    sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'succeeded', 'failed', 'canceled', name='runstatus', native_enum=False, length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['edit_sessions.id'],
                           name='fk_agent_runs_session_id_edit_sessions', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'],
                            name='fk_agent_runs_user_id_users', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_session_id'), 'agent_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.add_column('tool_runs', sa.Column('session_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_tool_runs_session_id'), 'tool_runs', ['session_id'], unique=False)
    op.create_foreign_key('fk_tool_runs_session_id_edit_sessions', 'tool_runs',
                          'edit_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tool_runs_session_id_edit_sessions', 'tool_runs', type_='foreignkey')
    op.drop_index(op.f('ix_tool_runs_session_id'), table_name='tool_runs')
    op.drop_column('tool_runs', 'session_id')
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_session_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
